export const featuredProperties = [
  {
    id: "p-1",
    nama_property: "Aston Villas Type A",
    group: "Mentari",
    lebar: 6,
    panjang: 17.8,
    hadap: ["Utara"],
    tipe: "villa",
    tingkat: 2,
    price: 1350000000,
    carport: true,
    status: "in_stock",
    siap: "siap_huni",
    kawasan: ["Krakatau", "Pancing"],
    unit: "Ready Siap huni",
    maps_link: "https://maps.google.com/maps?q=medan",
    created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "p-2",
    nama_property: "Banyan Tree Blok A",
    group: "Project Ville",
    lebar: 4.5,
    panjang: 21.5,
    hadap: ["Timur", "Barat"],
    tipe: "ruko",
    tingkat: 2.5,
    price: 980000000,
    carport: false,
    status: "sold_out",
    siap: "siap_kosong",
    kawasan: ["Cemara Asri/Kuala"],
    unit: "Gate siap",
    created_at: "2026-05-02T00:00:00Z",
  },
  {
    id: "p-3",
    nama_property: "Mentari Corner Unit",
    group: "Mentari",
    lebar: 5,
    panjang: 20,
    hadap: ["Selatan"],
    tipe: "ruko",
    tingkat: 3,
    price: 1200000000,
    carport: true,
    status: "in_stock",
    siap: "siap_huni_renovasi",
    kawasan: ["Helvetia"],
    unit: "Renovasi ringan",
    created_at: "2026-05-03T00:00:00Z",
  },
];

export const allProperties = [
  ...featuredProperties,
  {
    id: "p-4",
    nama_property: "Villa Harmoni",
    group: "Permai 123",
    lebar: 7,
    panjang: 19,
    hadap: ["Barat"],
    tipe: "villa",
    tingkat: 2,
    price: 1750000000,
    carport: true,
    status: "in_stock",
    siap: "siap_huni",
    kawasan: ["Tembung"],
    unit: "Ready premium",
    created_at: "2026-05-04T00:00:00Z",
  },
  {
    id: "p-5",
    nama_property: "Krakatau Residence D7",
    group: "Krakatau Residence",
    lebar: 4,
    panjang: 18,
    hadap: ["Utara", "Timur"],
    tipe: "ruko",
    tingkat: 2,
    price: 890000000,
    carport: false,
    status: "in_stock",
    siap: "siap_kosong",
    kawasan: ["Krakatau"],
    unit: "Siap finishing",
    created_at: "2026-05-05T00:00:00Z",
  },
];

export const adminAccounts = [
  {
    id: "u-1",
    name: "Raka Pratama",
    email: "admin@primeproperty.id",
    is_active: true,
    created_at: "2026-04-10",
  },
  {
    id: "u-2",
    name: "Sarah Wijaya",
    email: "sarah.admin@primeproperty.id",
    is_active: false,
    created_at: "2026-04-15",
  },
];

export const auditLogs = [
  {
    id: 1,
    waktu: "2026-05-24 10:30 WIB",
    user: "Superadmin",
    aksi: "create",
    entitas: "property",
    detail: "Membuat Aston Villas Type A",
  },
  {
    id: 2,
    waktu: "2026-05-24 11:10 WIB",
    user: "Superadmin",
    aksi: "update",
    entitas: "property",
    detail: "Mengubah status Banyan Tree Blok A",
  },
];
